CREATE DATABASE IF NOT EXISTS data_Siswa;

USE data_Siswa;

CREATE TABLE siswa (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(100) NOT NULL,
    alamat VARCHAR(100) NOT NULL,
    tgl_Siswa date NOT NULL,
    jurusan VARCHAR(50) NOT NULL,
    updateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
